
- name: Configurar servidores
  hosts: servidores
  become: true
  tasks:
    - name: Actualizar paquetes
      apt:
        update_cache: yes

    - name: Crear usuario itla
      user:
        name: itla
        state: present

    - name: Crear carpeta app
      file:
        path: /home/itla/app
        state: directory
        owner: itla

    - name: Crear archivo hola.txt
      copy:
        content: "¡Hola desde Ansible!"
        dest: /home/itla/app/hola.txt
        owner: itla

    - name: Instalar cowsay y htop
      apt:
        name:
          - cowsay
          - htop
        state: present
